(function () {
  "use strict";
  var T = {
    en: { back: "Back to vehicles", home: "Home", vehicles: "Vehicles", loading: "Loading vehicle...", ready: "EXPORT READY", price: "FOB export reference", quote: "Request export quote", whats: "WhatsApp", stock: "Available stock", overview: "Overview", overviewK: "Vehicle profile", overviewCopy: "Prepared for overseas dealers, importers and fleet buyers. Final availability is matched by trim, colour, quantity and destination port.", specs: "Specifications", specK: "Technical data", vehicleGroup: "Vehicle dimensions", powerGroup: "Powertrain & ownership", equipment: "Equipment", equipmentK: "Configuration", export: "Export information", exportK: "B2B supply", related: "Related vehicles", relatedK: "Explore the range", cta: "Build your next order with China supply.", body: "Body type", year: "Model year", drive: "Drivetrain", range: "Range", power: "Power", seats: "Seats", dimensions: "Dimensions", wheelbase: "Wheelbase", battery: "Battery / energy", engine: "Engine", transmission: "Transmission", warranty: "Warranty", tires: "Tyres", market: "Target markets", colors: "Available colours", route: "Export route", terms: "Trade terms", lead: "Lead time", note: "FOB reference pricing excludes destination duties and local charges. Final FOB/CIF pricing depends on trim, order quantity, colour, production date, destination port and freight schedule. Contact our export team for inspection documents and a proforma invoice." },
    zh: { back: "返回车辆资源", home: "首页", vehicles: "车辆资源", loading: "正在加载车型...", ready: "可出口车型", price: "FOB 出口参考价", quote: "获取出口报价", whats: "WhatsApp", stock: "现货库存", overview: "车型概览", overviewK: "车辆档案", overviewCopy: "面向海外经销商、进口商和车队采购商供应，可根据配置、颜色、采购数量和目的港匹配工厂与港口现货。", specs: "技术参数", specK: "完整参数", vehicleGroup: "车身参数", powerGroup: "动力与保障", equipment: "配置与颜色", equipmentK: "车辆配置", export: "出口信息", exportK: "B2B 采购", related: "相关推荐", relatedK: "继续浏览车型", cta: "从中国供应链开始你的下一笔采购。", body: "车身形式", year: "车型年份", drive: "驱动形式", range: "续航里程", power: "最大功率", seats: "座位数", dimensions: "车身尺寸", wheelbase: "轴距", battery: "电池 / 能源", engine: "发动机", transmission: "变速箱", warranty: "质保", tires: "轮胎", market: "目标市场", colors: "可选颜色", route: "出口路线", terms: "贸易条款", lead: "交付周期", note: "FOB 参考价格不含目的国关税及当地费用。最终 FOB/CIF 价格取决于配置、采购数量、颜色、生产日期、目的港和船期。请联系出口团队获取验车资料和形式发票。" },
    ar: { back: "العودة إلى المركبات", home: "الرئيسية", vehicles: "المركبات", loading: "جار تحميل المركبة...", ready: "جاهز للتصدير", price: "سعر FOB المرجعي", quote: "طلب عرض تصدير", whats: "واتساب", stock: "المخزون المتاح", overview: "نظرة عامة", overviewK: "ملف المركبة", overviewCopy: "متاحة للموزعين والمستوردين ومشتري الأساطيل في الأسواق الخارجية.", specs: "المواصفات", specK: "البيانات الفنية", vehicleGroup: "أبعاد المركبة", powerGroup: "المحرك والملكية", equipment: "التجهيزات", equipmentK: "التكوين", export: "معلومات التصدير", exportK: "توريد B2B", related: "مركبات ذات صلة", relatedK: "استكشف المجموعة", cta: "ابدأ طلبك التالي من سلسلة التوريد الصينية.", body: "الهيكل", year: "السنة", drive: "الدفع", range: "المدى", power: "القدرة", seats: "المقاعد", dimensions: "الأبعاد", wheelbase: "قاعدة العجلات", battery: "البطارية", engine: "المحرك", transmission: "ناقل الحركة", warranty: "الضمان", tires: "الإطارات", market: "الأسواق", colors: "الألوان", route: "مسار التصدير", terms: "شروط التجارة", lead: "مدة التوريد", note: "السعر المرجعي لا يشمل رسوم وضرائب بلد الوجهة. يعتمد السعر النهائي على الفئة والكمية والميناء والشحن." },
    ru: { back: "Назад к автомобилям", home: "Главная", vehicles: "Автомобили", loading: "Загрузка автомобиля...", ready: "ГОТОВ К ЭКСПОРТУ", price: "Ориентир FOB", quote: "Запросить цену", whats: "WhatsApp", stock: "В наличии", overview: "Обзор", overviewK: "Профиль автомобиля", overviewCopy: "Поставка для зарубежных дилеров, импортеров и автопарков.", specs: "Характеристики", specK: "Технические данные", vehicleGroup: "Размеры автомобиля", powerGroup: "Силовая установка", equipment: "Оснащение", equipmentK: "Комплектация", export: "Экспортная информация", exportK: "B2B поставка", related: "Похожие модели", relatedK: "Вся линейка", cta: "Начните следующую закупку с поставок из Китая.", body: "Кузов", year: "Год", drive: "Привод", range: "Запас хода", power: "Мощность", seats: "Места", dimensions: "Размеры", wheelbase: "Колесная база", battery: "Батарея", engine: "Двигатель", transmission: "Трансмиссия", warranty: "Гарантия", tires: "Шины", market: "Рынки", colors: "Цвета", route: "Маршрут", terms: "Условия", lead: "Срок поставки", note: "Ориентировочная цена FOB не включает пошлины страны назначения. Итоговая цена зависит от комплектации, количества, порта и фрахта." }
  };
  var facts = { "byd-song-plus": { dimensions: "4775 × 1890 × 1670 mm", wheelbase: "2765 mm", seats: "5", battery: "Blade Battery / DM-i", transmission: "E-CVT", price: "USD 18,900–24,500 FOB" }, "byd-seagull": { dimensions: "3780 × 1715 × 1540 mm", wheelbase: "2500 mm", seats: "4", battery: "30.08 / 38.88 kWh LFP", transmission: "Single-speed EV", price: "USD 9,500–12,500 FOB" }, "chery-tiggo8-pro": { dimensions: "4722 × 1860 × 1745 mm", wheelbase: "2710 mm", seats: "5 / 7", battery: "Petrol", transmission: "7-speed DCT", price: "USD 17,800–23,800 FOB" }, "geely-monjaro": { dimensions: "4770 × 1895 × 1689 mm", wheelbase: "2845 mm", seats: "5", battery: "Petrol", transmission: "8-speed AT", price: "USD 22,500–28,900 FOB" }, "haval-h6": { dimensions: "4683 × 1886 × 1730 mm", wheelbase: "2738 mm", seats: "5", battery: "Petrol", transmission: "7-speed DCT", price: "USD 14,800–20,800 FOB" }, "zeekr-001": { dimensions: "4977 × 1999 × 1533 mm", wheelbase: "3005 mm", seats: "5", battery: "95 / 100 kWh", transmission: "Single-speed EV", price: "USD 39,800–52,800 FOB" } };
  var vehicle, settings, lang = "en";
  function $(id) { return document.getElementById(id); }
  function esc(v) { return String(v == null ? "" : v).replace(/[&<>"']/g, function (c) { return { "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" }[c]; }); }
  function list(v) { return Array.isArray(v) ? v : String(v || "").split(/\r?\n|,/).map(function (x) { return x.trim(); }).filter(Boolean); }
  function textField(v, fallback) { return v == null || v === "" ? fallback || "" : v; }
  function setLang(next) { lang = T[next] ? next : "en"; localStorage.setItem("aex_lang", lang); document.documentElement.lang = lang; document.documentElement.dir = lang === "ar" ? "rtl" : "ltr"; document.querySelectorAll("[data-lang]").forEach(function (b) { b.classList.toggle("active", b.dataset.lang === lang); }); render(); }
  function spec(label, val) { return val ? '<div class="spec-row"><span>' + esc(label) + '</span><b>' + esc(val) + '</b></div>' : ""; }
  function render() {
    if (!vehicle) return; var t = T[lang], f = facts[vehicle.id] || {}, gallery = list(vehicle.gallery && vehicle.gallery.length ? vehicle.gallery : [vehicle.image]).filter(Boolean);
    document.title = vehicle.brand + " " + vehicle.name + " | Zhaoshang Zhilian"; $("backLink").textContent = t.back; $("homeLink").textContent = t.home; $("vehiclesLink").textContent = t.vehicles; $("crumbName").textContent = vehicle.brand + " " + vehicle.name; $("eyebrow").textContent = (vehicle.year || "") + " · " + t.ready; $("title").textContent = vehicle.brand + " " + vehicle.name;
    var description = lang === "zh" ? textField(vehicle.detailZh || vehicle.descZh, t.overviewCopy) : lang === "ar" ? textField(vehicle.detailAr || vehicle.detailEn || vehicle.descEn, t.overviewCopy) : lang === "ru" ? textField(vehicle.detailRu || vehicle.detailEn || vehicle.descEn, t.overviewCopy) : textField(vehicle.detailEn || vehicle.descEn, t.overviewCopy);
    $("description").textContent = description; $("priceLabel").textContent = t.price; $("price").textContent = vehicle.exportPrice || f.price || "Contact for quote"; $("stock").textContent = t.stock + ": " + (+vehicle.stock || 0) + " units"; $("marketNote").textContent = textField(lang === "zh" ? vehicle.marketZh : vehicle.marketEn, "Global dealer supply");
    $("mainImage").src = gallery[0] || ""; $("mainImage").alt = vehicle.brand + " " + vehicle.name; $("galleryCount").textContent = gallery.length + " photos"; $("thumbs").innerHTML = gallery.map(function (src, i) { return '<button class="thumb ' + (i === 0 ? "active" : "") + '" data-src="' + esc(src) + '"><img src="' + esc(src) + '" alt=""></button>'; }).join(""); document.querySelectorAll(".thumb").forEach(function (b) { b.onclick = function () { document.querySelectorAll(".thumb").forEach(function (x) { x.classList.remove("active"); }); b.classList.add("active"); $("mainImage").src = b.dataset.src; }; });
    var chips = [vehicle.type && String(vehicle.type).toUpperCase(), vehicle.bodyType || vehicle.categoryEn, vehicle.year].filter(Boolean); $("chips").innerHTML = chips.map(function (x) { return '<span class="chip">' + esc(x) + '</span>'; }).join("");
    $("overviewKicker").textContent = t.overviewK; $("overviewTitle").textContent = t.overview; $("overviewCopy").textContent = t.overviewCopy; $("specKicker").textContent = t.specK; $("specTitle").textContent = t.specs; $("vehicleGroupTitle").textContent = t.vehicleGroup; $("powerGroupTitle").textContent = t.powerGroup; $("equipmentKicker").textContent = t.equipmentK; $("featureTitle").textContent = t.equipment; $("exportKicker").textContent = t.exportK; $("exportTitle").textContent = t.export; $("relatedKicker").textContent = t.relatedK; $("relatedTitle").textContent = t.related; $("ctaTitle").textContent = t.cta;
    $("anchorOverview").textContent = t.overview; $("anchorSpecs").textContent = t.specs; $("anchorEquipment").textContent = t.equipment; $("anchorExport").textContent = t.export; $("quick").innerHTML = [[t.body, vehicle.bodyType || vehicle.categoryEn], [t.year, vehicle.year], [t.drive, vehicle.drivetrain], [t.range, vehicle.range], [t.power, vehicle.power], [t.seats, vehicle.seats || f.seats], [t.market, lang === "zh" ? vehicle.marketZh : vehicle.marketEn], [t.stock, (+vehicle.stock || 0) + " units"]].filter(function (x) { return x[1]; }).map(function (x) { return '<div class="quick-item"><span>' + esc(x[0]) + '</span><b>' + esc(x[1]) + '</b></div>'; }).join("");
    $("vehicleSpecs").innerHTML = spec(t.dimensions, vehicle.dimensions || f.dimensions) + spec(t.wheelbase, vehicle.wheelbase || f.wheelbase) + spec(t.seats, vehicle.seats || f.seats) + spec(t.body, vehicle.bodyType || vehicle.categoryEn); $("powerSpecs").innerHTML = spec(t.battery, vehicle.battery || f.battery) + spec(t.engine, vehicle.engine) + spec(t.transmission, vehicle.transmission || f.transmission) + spec(t.power, vehicle.power) + spec(t.range, vehicle.range) + spec(t.drive, vehicle.drivetrain) + spec(t.warranty, vehicle.warranty) + spec(t.tires, vehicle.tires);
    var highlights = list(vehicle.highlights && vehicle.highlights[lang] || vehicle.highlights && vehicle.highlights.en || vehicle.highlights && vehicle.highlights.zh); $("highlights").innerHTML = highlights.length ? highlights.map(function (x) { return "<li>" + esc(x) + "</li>"; }).join("") : "<li>Factory verified vehicle resource</li><li>Pre-export inspection available</li><li>Dealer volume pricing available</li>"; $("features").innerHTML = list(vehicle.features).map(function (x) { return '<span class="feature">' + esc(x) + '</span>'; }).join(""); $("colors").innerHTML = list(vehicle.colors).length ? '<strong style="width:100%;display:block;margin-top:22px;margin-bottom:8px">' + esc(t.colors) + '</strong>' + list(vehicle.colors).map(function (x) { var name = typeof x === "object" ? x.name : x; var hex = typeof x === "object" ? x.hex : "#d7dade"; return '<span class="color"><i style="background:' + esc(hex) + '"></i>' + esc(name) + '</span>'; }).join("") : "";
    $("notes").textContent = vehicle.exportNotes || t.note; $("exportGrid").innerHTML = [[t.market, lang === "zh" ? vehicle.marketZh : vehicle.marketEn || "Global"], [t.route, "China port → destination port"], [t.terms, "FOB / CIF by request"], [t.lead, "Confirmed per order"]].map(function (x) { return '<div><span>' + esc(x[0]) + '</span><b>' + esc(x[1]) + '</b></div>'; }).join(""); bindQuotes(t); renderRelated(); $("loading").hidden = true; $("page").hidden = false;
  }
  function bindQuotes(t) { var digits = String((settings && settings.whatsapp) || "8619310192287").replace(/\D/g, ""), url = "https://wa.me/" + digits + "?text=" + encodeURIComponent("Inquiry: " + vehicle.brand + " " + vehicle.name + " " + (vehicle.year || "")); $("quoteBtn").textContent = t.quote; $("bottomQuote").textContent = t.quote; $("mobileQuote").textContent = t.quote; $("waBtn").textContent = t.whats; $("waBtn").href = url; [$("quoteBtn"), $("bottomQuote"), $("mobileQuote")].forEach(function (b) { b.onclick = function () { location.href = url; }; }); }
  function renderRelated() { var others = window.__vehicleRows || []; $("related").innerHTML = others.filter(function (v) { return v.id !== vehicle.id && v.published !== false; }).slice(0, 3).map(function (v) { return '<a class="related" href="vehicle.html?id=' + encodeURIComponent(v.id) + '"><img src="' + esc(v.image || (v.gallery || [])[0] || "") + '" alt=""><b>' + esc(v.brand + " " + v.name) + '</b><small>' + esc(v.exportPrice || "Export quote") + '</small></a>'; }).join(""); }
  async function load() { try { lang = localStorage.getItem("aex_lang") || "en"; var id = new URLSearchParams(location.search).get("id"); if (!id) throw Error("Missing vehicle id"); var cfg = window.AUTOEXPORT_SUPABASE, db = window.supabase.createClient(cfg.url, cfg.publishableKey), results = await Promise.all([db.from("vehicles").select("id,data,published").eq("id", id).single(), db.from("vehicles").select("id,data,published").eq("published", true).order("sort_order"), db.from("site_settings").select("whatsapp").eq("id", "main").maybeSingle()]); if (results[0].error) throw results[0].error; vehicle = Object.assign({}, results[0].data.data, { id: results[0].data.id, published: results[0].data.published }); window.__vehicleRows = (results[1].data || []).map(function (r) { return Object.assign({}, r.data, { id: r.id, published: r.published }); }); settings = results[2].data || {}; setLang(lang); } catch (e) { $("loading").classList.add("error"); $("loading").textContent = "Vehicle not found / 未找到该车型"; } }
  document.querySelectorAll("[data-lang]").forEach(function (b) { b.onclick = function () { setLang(b.dataset.lang); }; }); load();
})();
